### ISSUE TITLE
Drop dependency on Microsoft HTTP Client Libraries

### ISSUE THREAD

**Issue by rzontar** [Ingenico-ePayments/connect-sdk-dotnet#1]
Since this Package targets .Net 4.5 and above, I believe the Nuget Package `Microsoft.Net.Http` is redundant, since `System.Net.Http` is already part of the .Net Framework since Version 4.5. 

When dropping the dependency following Packages could be removed:
`<package id="Microsoft.Bcl" version="1.1.10" targetFramework="net45" />`
`<package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="net45" />`
`<package id="Microsoft.Net.Http" version="2.2.29" targetFramework="net45" />`

**Comment by rob-spoor** [comment]
For your information, the changes we are making for https://github.com/Ingenico-ePayments/connect-sdk-dotnet/issues/3 will see a cleaned up dependency list. These dependencies will no longer be required.

**Comment by rob-spoor** [comment]
These dependencies have now been dropped with the new .NET Standard compatible release.
