### ISSUE TITLE
Can I use this SDK for physical devices like Desk 32xx ?

### ISSUE THREAD

**Issue by AndrewEastwood** [Ingenico-ePayments/connect-sdk-dotnet#13]
Or maybe you can advise where we can get sdk for communication with that?

**Comment by rikvanthof** [comment]
This SDK is using the Connect SDK to process online (ecommerce) payments only. It can't be used to connect to payment terminals. Maybe you can find more information on https://developer.ingenico.com regarding the options provided by Ingenico to use SDKs to connect to their terminals.
