### ISSUE TITLE
Remove/Disable Remember me checkbox for future reference 

### ISSUE THREAD

**Issue by syedsaadabbasi** [Ingenico-ePayments/connect-sdk-dotnet#14]
![image](https://user-images.githubusercontent.com/12624905/200811256-10f1b8fc-89a7-4318-aafe-3f3ae4b77ca7.png)

Hello 

Is there bit or option available to remove or disable this remember me checkbox using Ingenico Connect SDK ??

**Comment by rikvanthof** [comment]
You can disable the 'Remember my details...' option for any variant of the MyCheckout hosted payment pages using the MyCheckout Editor. By logging into the configuration center you can enter the MyCheckout Editor by navigating to the Look and feel menu option. Once in the editor you will find the option to disable (or enable) the 'Remember my details...' option in the Content styling block in the left navigation by unchecking the Remember Me option.
![Remember me option](https://user-images.githubusercontent.com/8860287/200819272-5d54c9db-69d0-4f1c-ba5b-a46fb7a71d02.png)

**Comment by syedsaadabbasi** [comment]
Thanks @rikvanthof for quick response.

I need to make it configurable based on condition, I can create multiple template pages with this feature on and off, however is there any method or properties available in SDK, where I can configure this ??

**Comment by rob-spoor** [comment]
The API itself, and therefore also the SDK, does not support configuring this flag. However, you can create two (or more) look & feels (variants) - with and without the setting @rikvanthof mentioned. You can specify the variant to use through nested property `HostedCheckoutSpecificInput.Variant` of the `CreateHostedCheckoutRequest`.

From [Create hosted check - payload](https://epayments-api.developer-ingenico.com/s2sapi/v1/en_US/dotnet/hostedcheckouts/create.html?paymentPlatform=GLOBALCOLLECT#hostedcheckouts-create-payload):

> Description
>
> Using the Configuration Center it is possible to create multiple variations of your MyCheckout payment pages. By specifying a specific variant you can force the use of another variant then the default. This allows you to test out the effect of certain changes to your MyCheckout payment pages in a controlled manner. Please note that you need to specify the ID of the variant.

**Comment by syedsaadabbasi** [comment]
Thank you @rob-spoor for confirmation (y)

**Comment by rob-spoor** [comment]
You're welcome.

**Comment by syedsaadabbasi** [comment]
@rob-spoor @rikvanthof  

Any thoughts why I can't see this Remember Me checkbox under Content Styling ??

![image](https://user-images.githubusercontent.com/12624905/201011657-1e28ee20-68d2-4437-8dc0-6758d81643de.png)

**Comment by rikvanthof** [comment]
I had to check myself as well. The content styling is depended on the content that is being shown on the page you are looking at in the editor. This means that the option only shows up if you are editing the page of a payment product that allows the details to be remembered. You can select one of the card products in the View menu in the first top right dropdown. Once the payment product page is selected the 'Remember me' option will appear in the 'Content styling' menu in the left navigation. 
 
![Select Visa](https://user-images.githubusercontent.com/8860287/201037087-ca4306e2-570e-44a1-8081-aca036aa88a5.png)

**Comment by syedsaadabbasi** [comment]
Okay fair enough and on which field that payment selection is dependent, I can't see these options as well.

![image](https://user-images.githubusercontent.com/12624905/201045130-1607fc5d-5a91-4390-855a-b1321e0e131e.png)

is there any document available to customize template other then this https://epayments.developer-ingenico.com/documentation/hosted-payment-pages/

**Comment by rikvanthof** [comment]
Hmm, that looks a bit strange. I see the payment products on the underlying page, so this shows that they are available on your account. Which environment (sandbox, preproduction or production) are you seeing this and what is your merchantId? I'll try to dig a bit deeper to see why these products are not showing up for you in that menu.

**Comment by syedsaadabbasi** [comment]
@rikvanthof  any luck what could be the issue ??

**Comment by syedsaadabbasi** [comment]
Worldline has created a ticket for this issue, there is issue with the Merchant that I am using, they are working on it.
