### ISSUE TITLE
What API version is the SDK using /  How to use v2 ? 

### ISSUE THREAD

**Issue by ArunoDh** [Ingenico-ePayments/connect-sdk-dotnet#16]
Hello,

The latest API version as stated `[here](https://support.direct.worldline-solutions.com/en/documentation/api/endpoints)` contains the path 'v2'.
But in the configuration of the sdk it is not allowed to add a path to the URL (exception from the sdk), nor is there an option to set a specific version ([docs](https://epayments.developer-ingenico.com/documentation/sdk/server/dotnet/)) 

Am i missing something to be able to use the latest version on production? 

Regards

**Comment by rob-spoor** [comment]
Hi @ArunoDh,

This SDK is for using the Connect API, as documented on https://epayments-api.developer-ingenico.com/. You're looking for the Direct SDK: https://github.com/wl-online-payments-direct/sdk-dotnet.

**Comment by ArunoDh** [comment]
@rob-spoor thanks for your fast reply. 
I will look into it!
