### ISSUE TITLE
 Does this SDK support dealing with Move/2500 devices?

### ISSUE THREAD

**Issue by Ahmed-Ghannnam** [Ingenico-ePayments/connect-sdk-dotnet#17]
First How can I specify devices in SDK to integrate with? is there configuration or something like that?
How can I integrate the Ingenico Move/2500 POS terminal? Where can I find the SDK for the Move/2500 POS terminal?

**Comment by rikvanthof** [comment]
This SDK is meant to be used against the Worldline Connect API interface. This API is used to process e-commerce payments on multiple Worldline platforms like Global Collect, Worldline Online Payments Acceptance WOPA and others. The SDK is not meant for instore transactions that utilize a terminal. Please look at https://developer.ingenico.com/ for more information from Ingenico.

**Comment by Ahmed-Ghannnam** [comment]
Thank you for your attention to this matter.
 I am writing to seek clarification on point-related account registration

I have encountered an issue during the registration process. When attempting to sign in, I don't know what I have to enter under the "Contact" field on the "Sign up" page, so I entered my Gmail address too. However, I'm trying to login, I received the following message: "Your organization has not been approved yet, please wait until we process your registration." Could you kindly explain the approval process and provide an estimated timeframe for the registration to be processed?

I appreciate your assistance in addressing these inquiries and look forward to your prompt response. Thank you.
