### ISSUE TITLE
.Net Standard or .Net Core version is needed

### ISSUE THREAD

**Issue by AlexXx777** [Ingenico-ePayments/connect-sdk-dotnet#3]
Hi all,
It would be really greate to have a .Net Standard or .Net Core version of the client in order to be able to use it in a moder environment. We are currently hosting our .Net Core services in the Azure Linux docker containers and not able to use this one.

**Comment by engntsn** [comment]
@AlexXx777 I agree with you absolutely.

**Comment by rob-spoor** [comment]
We will investigate what is possible. We had a pull request before (https://github.com/Ingenico-ePayments/connect-sdk-dotnet/pull/2) but this would break the NuGet publishing process.

**Comment by rob-spoor** [comment]
We are working on creating a version that targets both .NET Framework 4.5 and .NET Standard 2.0 and 2.1. This will allow existing users to keep using it, while also allowing it to be used on non-Microsoft systems. We aim to get this version finalized as soon as possible.

**Comment by rob-spoor** [comment]
The latest release is now compatible with .NET Framework 4.5 and .NET Standard 2.0 and 2.1.
