### ISSUE TITLE
Net core 3.1 config

### ISSUE THREAD

**Issue by vishalpatel-te-zz** [Ingenico-ePayments/connect-sdk-dotnet#6]
I have net core 3.1 web app and trying to use this SDK. How do I configure in App.Setting
With below, it gives error that configuration not found.

 "ConnectSDK": {
  "connectTimeout": "5000",
  "socketTimeout": "30000",
  "maxConnections": "10",
  "authorizationType": "",
  "integrator": "",
  "apiEndpoint": {
  "host": "",
  "scheme": "https"
}
}

Any help would be appreciated.

**Comment by rob-spoor** [comment]
Because the SDK still needs to be compatible with .NET Framework 4.5, the configuration loading has not been updated. It still requires an `app.conf` or `web.conf` configuration file.

We suggest you use either use one of the methods in class `Factory` that takes an `IDictionary`, or create a `CommunicatorConfiguration` instance and set its properties manually. When using an `IDictionary`, you can lookup the keys in [CommunicatorConfiguration.cs](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/CommunicatorConfiguration.cs).

**Comment by vishalpatel-te-zz** [comment]
Awesome that worked!!

**Comment by vvangasam** [comment]
Hi Iam trying to connect ingenico device, but the methods which i am trying to call i am not able to find in sdk. can u help me to connect

**Comment by rob-spoor** [comment]
The methods in `Factory` that take an `IDictionary` can be found here:
* [Factory.cs (line 46)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L46)
* [Factory.cs (line 79)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L79)
* [Factory.cs (line 130)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L130)
* [Factory.cs (line 172)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L172)

The methods in `Factory` that take a manually created `CommunicatorConfiguration` can be found here:
* [Factory.cs (line 87)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L87)
* [Factory.cs (line 139)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L139)
* [Factory.cs (line 180)](https://github.com/Ingenico-ePayments/connect-sdk-dotnet/blob/master/connect-sdk-dotnet/Factory.cs#L180)

I suggest one of the two methods that immediately returns a `Client`, unless you need to configure the `Session` or re-use the `Communicator`.

**Comment by vvangasam** [comment]
In web config i had written like this 

<ConnectSDK connectTimeout="5000" socketTimeout="30000" maxConnections="10" authorizationType="got from config panel" integrator="abc"> <apiEndpoint host="eu.api-ingenico.com" scheme="https"></apiEndpoint> </ConnectSDK>

but i am getting "ExceptionMessage":"Unsupported Authorization",  where can i find host name

**Comment by rob-spoor** [comment]
Let's continue in https://github.com/Ingenico-ePayments/connect-sdk-dotnet/issues/7.
