### ISSUE TITLE
Is this lib suitable for Ingenico ISelf Trio

### ISSUE THREAD

**Issue by xevilmaxx** [Ingenico-ePayments/connect-sdk-dotnet#9]
Hi,
Currently we are trying to integrate Ingenico ISelf Trio in our project.
I still can't figure out if this library is just for interfacing with Ingenico Cloud service or if POS exposes HTTP API which a may use through this library.

Please **let me know if this lib can work with standalone device reachable over ethernet** or if there are some similar ready to use libraries that i can use to communicate with Ingenico devices.
Or i i have no choise and need implement whole protocol by myself.

**Comment by rob-spoor** [comment]
This library is only for interfacing with the Connect API: https://epayments-api.developer-ingenico.com/

**Comment by edsonlb** [comment]
Hi @rob-spoor, where is possible to find any information about the direct interface communication protocols using USB serial line or the Ethernet TCP/IP communication? #iSELF_EFT_POS

**Comment by rob-spoor** [comment]
@edsonlb you would need to ask Worldline themselves.
